openapi: 3.0.0
info:
  title: Coffee Order Service
  version: 1.0.0
paths:
  /health:
    get:
      summary: Get Health
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  # Additional properties if needed
  /{userId}:
    get:
      summary: Get User Orders
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: The ID of the user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        userId:
                          type: string
                        items:
                          type: array
                          items:
                            type: object
                            properties:
                              _id:
                                type: string
                              quantity:
                                type: integer
                              userId:
                                type: string
                              coffeeId:
                                type: string
                              createdAt:
                                type: string
                # Additional properties if needed
    post:
      summary: Create User Order
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: The ID of the user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                # Define properties of the request body if needed
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                      userId:
                        type: string
                      items:
                        type: array
                        items:
                          type: object
                          properties:
                            _id:
                              type: string
                            quantity:
                              type: integer
                            userId:
                              type: string
                            coffeeId:
                              type: string
                            createdAt:
                              type: string
                # Additional properties if needed
    delete:
      summary: Delete All User Orders
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: The ID of the user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      acknowledged:
                        type: boolean
                      deletedCount:
                        type: integer
                # Additional properties if needed
  /{userId}/{orderId}:
    delete:
      summary: Delete Order By Id
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: The ID of the user
        - in: path
          name: orderId
          required: true
          schema:
            type: string
          description: The ID of the order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                      userId:
                        type: string
                      items:
                        type: array
                        items:
                          type: object
                          properties:
                            _id:
                              type: string
                            quantity:
                              type: integer
                            userId:
                              type: string
                            coffeeId:
                              type: string
                            createdAt:
                              type: string
                # Additional properties if needed
