openapi: 3.0.0
info:
  title: Combined API Specification
  version: 1.0.0
paths:
  /health:
    get:
      summary: Health Check
      responses:
        '200':
          description: OK
  /{userId}:
    get:
      summary: Get User Orders
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: User Orders Retrieved
        '400':
          description: Bad Request
    post:
      summary: Create User Order
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
      responses:
        '201':
          description: Order Created
        '400':
          description: Bad Request
    delete:
      summary: Delete All Orders for User
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: All Orders Deleted
        '400':
          description: Bad Request
  /{userId}/{orderId}:
    delete:
      summary: Delete Order by ID
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      - name: orderId
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Order Deleted by Id
        '400':
          description: Bad Request
        '404':
          description: Order Not Found
components:
  schemas: {}
